### ISSUE TITLE
`AssociatePackageFunction` がタイムアウトする

### ISSUE THREAD

**Issue by ymhiroki** [aws-samples/opensearch-intelligent-search-jp#1]
`PythonFunctin` のデフォルトタイムアウトが3秒 ([FunctionOptions](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.FunctionOptions.html#timeout)) で、処理が終わらなかった場合にデプロイに失敗する。
該当箇所はここ [opensearch.ts](https://github.com/aws-samples/opensearch-intelligent-search-jp/blob/8e18ae0f84f9e047351833d081894e7a595434aa/packages/cdk/lib/constructs/opensearch.ts#L116)

CloudFormation コンソールでのエラー

```
Received response status [FAILED] from custom resource. Message returned: Error: 2024-07-22T01:03:02.782Z 68491297-52dd-47e7-b1b3-9f6970f64f7f Task timed out after 3.01 seconds Logs: /aws/lambda/OpensearchIntelligentSear-OpenSearchAssociatePacka-RMpXXy3nRGum at invokeUserFunction (/var/task/framework.js:2:6) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async onEvent (/var/task/framework.js:1:369) at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 2fc38ca5-7a4b-46fc-8aba-cc0a5f809c0d)
```

`npm run cdk:deploy` 時のエラー全文

```
OpensearchIntelligentSearchJpStack: creating CloudFormation changeset...
10:03:03 | CREATE_FAILED        | AWS::CloudFormation::CustomResource      | OpenSearchMyResourceD6C22B66
Received response status [FAILED] from custom resource. Message returned: Error: 2024-07-22T01:03:02.782Z 68491297-52dd-47e7-b1b3-9f6970f64f7f Task timed out after 3
.01 seconds

Logs: /aws/lambda/OpensearchIntelligentSear-OpenSearchAssociatePacka-RMpXXy3nRGum

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 2fc38ca5-7a4b-46fc-8aba-cc0a5f809c0d)


 ❌  OpensearchIntelligentSearchJpStack failed: Error: The stack named OpensearchIntelligentSearchJpStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: 2024-07-22T01:03:02.782Z 68491297-52dd-47e7-b1b3-9f6970f64f7f Task timed out after 3.01 seconds

Logs: /aws/lambda/OpensearchIntelligentSear-OpenSearchAssociatePacka-RMpXXy3nRGum

    at invokeUserFunction (/var/task/framework.js:2:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 2fc38ca5-7a4b-46fc-8aba-cc0a5f809c0d)
    at FullCloudFormationDeployment.monitorDeployment (/Users/yhirokiy/works/opensearch-intelligent-search-jp/node_modules/aws-cdk/lib/index.js:451:10568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/yhirokiy/works/opensearch-intelligent-search-jp/node_modules/aws-cdk/lib/index.js:454:199716)
    at async /Users/yhirokiy/works/opensearch-intelligent-search-jp/node_modules/aws-cdk/lib/index.js:454:181438

 ❌ Deployment failed: Error: The stack named OpensearchIntelligentSearchJpStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: 2024-07-22T01:03:02.782Z 68491297-52dd-47e7-b1b3-9f6970f64f7f Task timed out after 3.01 seconds

Logs: /aws/lambda/OpensearchIntelligentSear-OpenSearchAssociatePacka-RMpXXy3nRGum

    at invokeUserFunction (/var/task/framework.js:2:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 2fc38ca5-7a4b-46fc-8aba-cc0a5f809c0d)
    at FullCloudFormationDeployment.monitorDeployment (/Users/yhirokiy/works/opensearch-intelligent-search-jp/node_modules/aws-cdk/lib/index.js:451:10568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/yhirokiy/works/opensearch-intelligent-search-jp/node_modules/aws-cdk/lib/index.js:454:199716)
    at async /Users/yhirokiy/works/opensearch-intelligent-search-jp/node_modules/aws-cdk/lib/index.js:454:181438

The stack named OpensearchIntelligentSearchJpStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: 2024-07-22T01:03:02.782Z 68491297-52dd-47e7-b1b3-9f6970f64f7f Task timed out after 3.01 seconds

Logs: /aws/lambda/OpensearchIntelligentSear-OpenSearchAssociatePacka-RMpXXy3nRGum

    at invokeUserFunction (/var/task/framework.js:2:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1676) (RequestId: 2fc38ca5-7a4b-46fc-8aba-cc0a5f809c0d)
opensearch-intelligent-search-jp % npm run cdk:deploy
```

**Comment by tkyaaida** [comment]
上記PRにて対応
